[package]
name = "ark-testing"
version = "0.1.0"
edition = "2021"

[dependencies]
aspd-rpc-client = { path = "../aspd-rpc-client" }
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
bitcoin.workspace = true
bitcoincore-rpc = "0.19.0"
env_logger.workspace = true
log.workspace = true
fern.workspace = true
chrono.workspace = true
portpicker = "0.1.1"
rand.workspace = true
regex = "1.10.5"
tokio.workspace = true
tonic.workspace = true
which = "6.0.1"
